'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { CalendarCheck, History, SlidersHorizontal } from 'lucide-react';
import { localDate, type Course, type Slot } from '@/lib/model';
import { attendanceRisks, attendanceSummary } from '@/lib/academic-calculations';
import type { ClassOccurrence } from '@/lib/academic-types';
import { AcademicEmpty, CourseAcademicForm, Decimal, Field, FormError, PeriodManager, type AcademicProps } from './academic-shared';

export function AttendanceBar({ percent, requirement }: {percent: number | null; requirement: string}) {
  return <div className="attendance-track" role="img" aria-label={`${percent === null ? 'No recorded attendance' : `${percent.toFixed(4)}% recorded attendance`}; ${requirement === '' ? 'requirement not set' : `${requirement}% required`}`}><span style={{width:`${percent ?? 0}%`}}/>{requirement !== '' && <i style={{left:`${Number(requirement)}%`}}/>}</div>;
}
export function AttendanceControls({ occurrence:o, now, save, disabled }: Pick<AcademicProps,'now'|'save'|'disabled'> & {occurrence: ClassOccurrence}) {
  const unavailable = disabled || o.cancelled || Date.parse(o.start) > now;
  return <div className="attendance-controls" aria-label="Attendance correction"><button className="secondary" disabled={unavailable} aria-pressed={o.attendance === 'attended'} onClick={() => void save('attendance',{id:o.id,status:'attended'})}>Attended</button><button className="secondary" disabled={unavailable} aria-pressed={o.attendance === 'missed'} onClick={() => void save('attendance',{id:o.id,status:'missed'})}>Missed</button>{o.attendance && <button className="text-button" disabled={unavailable} onClick={() => void save('attendance',{id:o.id,status:''})}>Clear record</button>}</div>;
}
export function AttendancePreview(props: AcademicProps) {
  const rows = attendanceRisks(props.data,props.now).slice(0,3);
  return <section className="panel academic-preview"><div className="panel-heading"><h2><CalendarCheck size={19}/>Attendance</h2><Link href="/attendance">View attendance →</Link></div>{rows.length ? rows.map(r => <div className="academic-preview-row" key={r.course.id}><Link href={`/attendance?course=${r.course.id}`}><strong>{r.course.name}</strong></Link><span>{r.attended}/{r.total} recorded · {r.state}</span><AttendanceBar percent={r.percent} requirement={r.course.attendanceRequirement}/><p>{r.advice}</p><small>{r.unmarked} known past classes unmarked. Based on recorded history only.</small></div>) : <div className="empty"><h3>No attendance recorded</h3><p>Add a course and class to get started.</p></div>}</section>;
}
export default function Attendance(props: AcademicProps) {
  const {data,now,save,disabled,error} = props, query = useSearchParams(), router = useRouter();
  const [filter,setFilter] = useState('all'), [limit,setLimit] = useState(30);
  const period = query.get('period') || 'all';
  const courses = data.courses.filter(c => period === 'all' || c.periodId === (period === 'unassigned' ? '' : period));
  const course = courses.find(c => c.id === query.get('course')) || courses[0];
  const select = (p: string, c: string) => {setLimit(30);router.push(`/attendance?period=${encodeURIComponent(p)}&course=${encodeURIComponent(c)}`,{scroll:false});};
  const rows = attendanceRisks(data,now,period === 'unassigned' ? '' : period);
  const today = localDate(now,data.profile.timezone);
  const todays = data.classOccurrences.filter(o => courses.some(c => c.id === o.courseId && !c.archived) && localDate(Date.parse(o.start),data.profile.timezone) === today).sort((a,b) => a.start.localeCompare(b.start));
  const history = data.classOccurrences.filter(o => o.courseId === course?.id && (filter === 'all' || (filter === 'cancelled' ? o.cancelled : !o.cancelled && (o.attendance || 'unmarked') === filter))).sort((a,b) => b.start.localeCompare(a.start) || a.id.localeCompare(b.id));
  const summary = course ? attendanceSummary(data,course,now) : null;
  const format = (instant: string) => new Intl.DateTimeFormat('en-US',{timeZone:data.profile.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(instant));
  function classRow(o: ClassOccurrence) {
    return <article className="attendance-event" key={o.id}><div><strong>{data.courses.find(c => c.id === o.courseId)?.name}</strong><time dateTime={o.start}>{format(o.start)} – {new Intl.DateTimeFormat('en-US',{timeZone:data.profile.timezone,timeStyle:'short'}).format(new Date(o.end))}</time><span className="muted">{o.room || 'Room not set'} · {o.cancelled ? 'Cancelled / non-held' : Date.parse(o.start)>now ? 'Future — marking unavailable' : o.attendance || 'Unmarked'}</span></div><AttendanceControls occurrence={o} {...props}/><details className="event-details"><summary>Correction details</summary><button className="text-button" disabled={disabled} onClick={() => { if (window.confirm(o.cancelled ? 'Restore this class as unmarked?' : 'Cancel this non-held class? Any attendance result will be cleared and excluded.')) void save('class-cancel',{id:o.id,cancelled:!o.cancelled,confirm:true}); }}>{o.cancelled ? 'Restore class' : 'Cancel non-held class'}</button>{o.changes.length ? <ul>{o.changes.map((h,i) => <li key={i}>{format(h.at)} · {h.action}</li>)}</ul> : <p className="fine">No corrections recorded.</p>}</details></article>;
  }
  return <div className="academic-workspace"><div className="toolbar"><Field label="Academic period"><select value={period} onChange={e => select(e.target.value,'')}><option value="all">All periods</option><option value="unassigned">Unassigned courses</option>{data.periods.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Link className="secondary" href="/gpa-planner">GPA planner →</Link></div>
    <PeriodManager {...props}/><details className="panel academic-details"><summary><SlidersHorizontal size={17}/> Attendance settings</summary><form className="academic-form details-content" onSubmit={e => {e.preventDefault();void save('attendance-default',{value:new FormData(e.currentTarget).get('value')});}}><Field label="Default requirement for new courses (%)"><Decimal name="value" value={data.defaultAttendance} optional/></Field><p className="fine">Blank means unset. Saving this default never changes existing courses. Each class has equal weight; advice assumes consecutive next classes and is not university permission.</p><FormError error={error}/><button className="primary" disabled={disabled}>Save new-course default</button></form></details>
    {!courses.length ? <section className="panel"><AcademicEmpty/></section> : <><div className="academic-stat-grid"><div><strong>{rows.filter(r => r.state === 'Below requirement').length}</strong><span>Below requirement</span></div><div><strong>{rows.filter(r => r.state === 'Close to limit').length}</strong><span>Close to limit</span></div><div><strong>{rows.reduce((n,r) => n+r.unmarked,0)}</strong><span>Known past classes unmarked</span></div></div><section className="panel"><div className="panel-heading"><h2>Recorded attendance</h2><span className="muted">Lowest-margin risks first</span></div>{rows.map(r => <article className="attendance-course" key={r.course.id}><div className="row-spread"><button className="text-button" onClick={() => select(period,r.course.id)}><strong>{r.course.name}</strong></button><span className={`pill ${r.state === 'Below requirement' ? 'red' : r.state === 'Close to limit' ? 'amber' : ''}`}>{r.state}</span></div><p>{r.attended} attended / {r.total} recorded · {r.missed} missed · {r.percent === null ? 'No percentage yet' : `${r.percent.toFixed(2)}%`} · {r.course.attendanceRequirement === '' ? 'Requirement not set' : `${r.course.attendanceRequirement}% required`}</p><AttendanceBar percent={r.percent} requirement={r.course.attendanceRequirement}/><p className="prediction">{r.advice}</p><p className="fine">Based on {r.total} recorded classes; {r.unmarked} known past classes unmarked. Earlier history may be incomplete.</p><Link className="inline-link" href={`/attendance?period=${encodeURIComponent(period)}&course=${r.course.id}#attendance-history`}>Review history →</Link></article>)}</section>
    <section className="panel"><div className="panel-heading"><h2><CalendarCheck size={18}/>Today’s classes</h2><span className="muted">{data.profile.timezone}</span></div>{todays.length ? todays.map(classRow) : <div className="empty"><h3>No classes today</h3><p>Add a dated class below or use your weekly timetable.</p></div>}</section>
    {course && <section className="panel" id="attendance-history"><div className="panel-heading"><h2><History size={18}/>Class history and corrections</h2></div><div className="details-content"><Field label="History course"><select value={course.id} onChange={e => select(period,e.target.value)}>{courses.map(c => <option key={c.id} value={c.id}>{c.name}{c.archived ? ' (archived)' : ''}</option>)}</select></Field><p className="fine">{summary?.total} recorded; {summary?.unmarked} known past classes unmarked. Future and cancelled classes do not count. No remaining-semester count is inferred from unknown boundaries.</p><Field label="History status"><select value={filter} onChange={e => {setFilter(e.target.value);setLimit(30);}}>{['all','attended','missed','unmarked','cancelled'].map(f => <option key={f} value={f}>{f[0].toUpperCase()+f.slice(1)}</option>)}</select></Field></div>{history.slice(0,limit).map(classRow)}{history.length === 0 && <p className="details-content muted">No classes match this filter.</p>}{history.length>limit && <button className="secondary" onClick={() => setLimit(limit+30)}>Show 30 more classes</button>}<details className="sub-details"><summary>Add a dated class, including missing history</summary><DatedClassForm key={course.id} course={course} {...props}/></details><details className="sub-details"><summary>Course period, attendance requirement, and policies</summary><CourseAcademicForm key={course.id} course={course} {...props}/></details><details className="sub-details"><summary>Change a future recurring schedule</summary>{data.slots.filter(s => s.courseId === course.id && (!s.untilDate || s.untilDate > today)).map(slot => <ScheduleForm key={slot.id} slot={slot} {...props}/>)}{!data.slots.some(s => s.courseId === course.id) && <p className="fine">Add a recurring class in Timetable first.</p>}</details></section>}</>}
  </div>;
}
function DatedClassForm({course,data,save,disabled,error}: AcademicProps & {course: Course}) {
  const [id,setId] = useState(crypto.randomUUID());
  return <form className="academic-form" onSubmit={async e => {e.preventDefault();const form=e.currentTarget;if(await save('dated-class',{...Object.fromEntries(new FormData(form)),id,courseId:course.id,timezone:data.profile.timezone})){form.reset();setId(crypto.randomUUID());}}}><Field label="Class date"><input name="date" type="date" required defaultValue={localDate(Date.now(),data.profile.timezone)}/></Field><div className="form-two"><Field label="Class start time"><input name="start" type="time" required defaultValue="09:00"/></Field><Field label="Class end time"><input name="end" type="time" required defaultValue="10:00"/></Field></div><Field label="Class room (optional)"><input name="room" maxLength={100}/></Field><p className="fine">Timezone: {data.profile.timezone}. Check history first to avoid entering the same held class twice. Same-day classes remain distinct.</p><FormError error={error}/><button className="primary" disabled={disabled}>Add dated class</button></form>;
}
function ScheduleForm({slot,save,disabled,error}: AcademicProps & {slot: Slot}) {
  const [newId,setNewId] = useState(crypto.randomUUID());
  return <form className="academic-form schedule-revision" onSubmit={async e => {e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(await save('schedule-revise',{...values,id:slot.id,newId,weekday:Number(values.weekday)}))setNewId(crypto.randomUUID());}}><p><strong>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][slot.weekday]} {slot.start}–{slot.end}</strong> · {slot.room || 'No room'} · {slot.timezone}</p><Field label="Change from date (future only)"><input type="date" name="effective" required/></Field><Field label="New weekday"><select name="weekday" defaultValue={slot.weekday}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i) => <option value={i} key={d}>{d}</option>)}</select></Field><div className="form-two"><Field label="New start time"><input name="start" type="time" defaultValue={slot.start} required/></Field><Field label="New end time"><input name="end" type="time" defaultValue={slot.end} required/></Field></div><Field label="New room"><input name="room" defaultValue={slot.room}/></Field><p className="fine">Past occurrences and corrections keep their original identities. Future occurrences from the effective date are replaced by this new recurrence.</p><FormError error={error}/><button className="primary" disabled={disabled}>Save future schedule</button></form>;
}
