'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { GraduationCap } from 'lucide-react';
import type { Course } from '@/lib/model';
import type { Assessment } from '@/lib/academic-types';
import { courseCalculation, semesterCalculation } from '@/lib/academic-calculations';
import { AcademicEmpty, CourseAcademicForm, Decimal, Field, FormError, PeriodManager, type AcademicProps } from './academic-shared';
import GradingRules, { CourseRuleForm, RulePreview } from './grading-rules';

export function CourseResult({course,...props}: AcademicProps & {course: Course}) {
  const calc = courseCalculation(props.data,course);
  return <div className="course-calculation"><div className="row-spread"><h3>{calc.state}</h3><span className="pill">Saved inputs</span></div><p className="prediction" data-testid="course-advice">{calc.advice}</p>
    <dl className="calculation-numbers"><div><dt>Secured final-score contribution</dt><dd>{calc.earned.fixed(2)} points</dd></div><div><dt>Average on graded work</dt><dd>{calc.gradedAverage ? `${calc.gradedAverage.fixed(2)}%` : 'No scored work'}</dd></div><div><dt>Remaining assessment weight</dt><dd>{calc.remaining.fixed(2)}%</dd></div><div><dt>Possible final raw range</dt><dd>{calc.valid ? `${calc.earned.fixed(2)}–${calc.maximum.fixed(2)}%` : 'Complete weights first'}</dd></div></dl>
    {calc.valid && <><div className="grade-chart" role="img" aria-label={calc.chart.map(s=>`${s.label}: ${s.value.toFixed(4)} weighted points`).join('; ')}>{calc.chart.map((s,i)=><span key={s.label} className={`segment segment-${i}`} style={{width:`${s.value}%`}}/>)}</div><ul className="chart-legend">{calc.chart.map((s,i)=><li key={s.label}><i className={`segment-${i}`}/>{s.label}: {s.value.toFixed(2)} points</li>)}</ul></>}
    {calc.target && <p className="fine">{course.target?.kind==='grade' ? `Grade target ${course.target.value}: lowest raw threshold ${calc.target.fixed(4)}% under the selected mapping policy.` : `Raw target ${calc.target.fixed(2)}% (not adjusted for grade rounding).`}</p>}
    {calc.final && !course.gradingPolicy && <p className="final-trail">Final raw {calc.earned.fixed(4)}%{calc.grade ? ` → mapped ${calc.grade.mapped.fixed(4)}% → ${calc.grade.label}${calc.rule?.scale !== 'percentage' ? ` → ${calc.grade.points} points` : ' (percentage only)'} · ${calc.rule?.name} v${calc.rule?.version}` : ' · No grading system selected; GPA unavailable.'}</p>}
    <p className="fine">Fixed positive weights only. Remaining marks are unknown, never assumed zero. Attendance and deadline completion do not create scores.</p>
  </div>;
}
export function GpaPreview(props: AcademicProps) {
  const selected = props.data.courses.filter(c=>!c.archived).find(c=>c.target) || props.data.courses.find(c=>!c.archived);
  return <section className="panel academic-preview"><div className="panel-heading"><h2><GraduationCap size={19}/>Academic target</h2><Link href="/gpa-planner">Open planner →</Link></div>{selected ? <div className="academic-preview-row"><Link href={`/gpa-planner?period=${selected.periodId || 'unassigned'}&course=${selected.id}`}><strong>{selected.name}</strong></Link><CourseResult course={selected} {...props}/></div> : <div className="empty"><h3>Build your academic picture</h3><p>Add a course, then enter assessment weights. Percentage planning works without a grade table.</p></div>}</section>;
}
export default function GpaPlanner(props: AcademicProps) {
  const {data,save,disabled,error} = props, query=useSearchParams(),router=useRouter();
  const periodId=query.get('period') || data.periods[0]?.id || 'unassigned';
  const courses=data.courses.filter(c=>c.periodId === (periodId==='unassigned'?'':periodId));
  const course=courses.find(c=>c.id===query.get('course')) || courses[0];
  const tab=query.get('tab')==='semester'?'semester':'course';
  const navigate=(period:string,id:string,nextTab=tab)=>router.push(`/gpa-planner?period=${encodeURIComponent(period)}&course=${encodeURIComponent(id)}&tab=${nextTab}`,{scroll:false});
  const result=semesterCalculation(data,periodId), calc=course?courseCalculation(data,course):null;
  return <div className="academic-workspace"><div className="toolbar"><Field label="Academic period"><select value={periodId} onChange={e=>navigate(e.target.value,'')}><option value="unassigned">Unassigned courses</option>{data.periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Link className="secondary" href="/attendance">Attendance →</Link></div><PeriodManager {...props}/><GradingRules {...props}/>
    <section className="panel gpa-summary"><div><span className="eyebrow">{periodId==='unassigned'?'SELECT A PERIOD FOR SEMESTER GPA':result.label.toUpperCase()}</span><strong className="gpa-value">{result.gpa?.fixed(2) || '—'}</strong><p>{result.included.length} of {result.courses.length} courses · {result.credits.fixed(2)} included credits</p>{result.gpa && <p className="fine">{result.quality.fixed(4)} quality points ÷ {result.credits.fixed(4)} credits = {result.gpa.fixed(6)} raw GPA.</p>}{result.incompatible && <p className="error">Incompatible grading scales or separate system lineages. GPA is withheld; no conversion is inferred.</p>}{result.period?.goal && <p>Semester goal: {result.period.goal}. {result.targetMet===null ? 'Not yet comparable.' : result.complete ? result.targetMet ? 'Goal achieved on the full-precision final result.' : 'Goal not achieved on the full-precision final result.' : result.targetMet ? 'Partial GPA is at or above the goal; semester achievement is not yet known.' : 'Partial GPA is below the goal; semester achievement is not yet known.'}</p>}</div><div><h3>Coverage details</h3>{result.excluded.length ? <ul>{result.excluded.map(e=><li key={e.course.id}><strong>{e.course.name}:</strong> {e.reason}</li>)}</ul> : <p className="fine">{result.complete ? 'All courses in this period have compatible final results and credits.' : 'Assign courses to an academic period to calculate its GPA.'}</p>}{result.incompatible && <ul>{result.included.map(i=><li key={i.course.id}>{i.course.name}: {i.rule.name} v{i.rule.version}, {i.rule.maxPoints}-point scale</li>)}</ul>}</div></section>
    <div className="segmented academic-tabs"><button aria-pressed={tab==='course'} onClick={()=>navigate(periodId,course?.id || '','course')}>Course planner</button><button aria-pressed={tab==='semester'} onClick={()=>navigate(periodId,course?.id || '','semester')}>Semester targets</button></div>
    {!courses.length && <section className="panel"><AcademicEmpty/>{data.courses.length>0 && <div className="details-content"><p>Assign an existing course to this period:</p>{data.courses.map(c=><details className="sub-details" key={c.id}><summary>{c.name}</summary><CourseAcademicForm course={c} {...props}/></details>)}</div>}</section>}
    {tab==='course' && course && <><section className="panel"><div className="details-content"><Field label="Planner course"><select value={course.id} onChange={e=>navigate(periodId,e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.name}{c.archived?' (archived)':''}</option>)}</select></Field><CourseResult course={course} {...props}/></div><details className="sub-details"><summary>Course period, credits, and institutional policies</summary><CourseAcademicForm key={course.id} course={course} {...props}/></details><details className="sub-details"><summary>Choose or remap grading version</summary><CourseRuleForm key={course.id+course.gradeRuleId} course={course} {...props}/>{calc?.rule && <RulePreview rule={calc.rule}/>}</details><details className="sub-details" open><summary>Course target</summary><TargetForm key={course.id+course.gradeRuleId} course={course} {...props}/></details></section>
    <section className="panel"><div className="panel-heading"><h2>Weighted assessments</h2><span className="pill">Total weight {calc?.total.fixed(2)}%</span></div>{calc?.rows.map(a=><div className="assessment-row" key={a.id}><div className="row-spread"><div><strong>{a.title}</strong><p>{a.score===''?'Ungraded / awaiting result':`${a.score}/${a.max} scored`} · {a.weight}% weight{a.due?` · date ${a.due}`:''}</p></div><span className="pill">{a.type}</span></div><details className="sub-details"><summary>Edit assessment or score</summary><AssessmentForm key={a.id} existing={a} course={course} {...props}/></details><button className="text-button" disabled={disabled} onClick={()=>{if(window.confirm(`Delete “${a.title}” and its score? This changes the assessment weight total.`))void save('assessment-delete',{id:a.id,courseId:course.id,confirm:true});}}>Delete assessment</button></div>)}<details className="sub-details" open><summary>Add an assessment</summary><AssessmentForm key={course.id} course={course} {...props}/></details></section></>}
    {tab==='semester' && <><section className="panel"><div className="panel-heading"><h2>Semester GPA goal</h2></div>{result.period ? <SemesterGoal key={result.period.id} {...props} periodId={result.period.id}/> : <p className="details-content">Create and select a named academic period before saving a semester goal.</p>}</section><section className="panel"><div className="panel-heading"><h2>Course targets and remaining work</h2></div><div className="academic-table-wrap" role="region" aria-label="Semester course target table" tabIndex={0}><table className="academic-table"><thead><tr><th>Course</th><th>Credits</th><th>Saved target</th><th>Requirement / missing data</th></tr></thead><tbody>{courses.map(c=>{const calculation=courseCalculation(data,c);return <tr key={c.id}><td><button className="text-button" onClick={()=>navigate(periodId,c.id,'course')}>{c.name}</button></td><td>{c.credits || 'Missing'}</td><td>{c.target?`${c.target.value}${c.target.kind==='raw'?'% raw':' grade'}`:'Not set'}</td><td><strong>{calculation.state}</strong><p>{calculation.advice}</p></td></tr>;})}</tbody></table></div><p className="fine details-content">A semester goal never assigns course targets automatically. Final, partial, and target values stay separate. No scenario values are stored as actual results.</p></section></>}
  </div>;
}
function TargetForm({course,data,save,disabled,error}: AcademicProps & {course: Course}) {
  const [kind,setKind]=useState(course.target?.kind || 'none');
  const rule=data.gradeRules.find(r=>r.id===course.gradeRuleId);
  return <form className="academic-form" onSubmit={e=>{e.preventDefault();void save('course-target',{...Object.fromEntries(new FormData(e.currentTarget)),id:course.id});}}><Field label="Target type"><select name="targetKind" value={kind} onChange={e=>setKind(e.target.value)}><option value="none">No target</option><option value="raw">Raw percentage</option><option value="grade">Grade from saved rules</option></select></Field>{kind==='raw' && <Field label="Raw percentage target"><Decimal name="value" value={course.target?.kind==='raw'?course.target.value:''}/></Field>}{kind==='grade' && <Field label="Target grade"><select required name="value" defaultValue={course.target?.kind==='grade'?course.target.value:''}><option value="">Choose a grade</option>{rule?.bands.map(b=><option key={b.label} value={b.label}>{b.label} · {b.lower}% mapped minimum{b.points?` · ${b.points} points`:''}</option>)}</select></Field>}{kind==='grade' && !rule && <p className="banner">Save and apply a grading system before choosing a grade target. Raw percentage planning is available now.</p>}<FormError error={error}/><button className="primary" disabled={disabled || (kind==='grade'&&!rule)}>Save course target</button></form>;
}
function AssessmentForm({course,existing,save,disabled,error}: AcademicProps & {course: Course;existing?: Assessment}) {
  const [id,setId]=useState(existing?.id || crypto.randomUUID());
  return <form className="academic-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await save('assessment',{...Object.fromEntries(new FormData(form)),id,courseId:course.id})){if(!existing){form.reset();setId(crypto.randomUUID());}}}}><Field label="Assessment title"><input name="title" required maxLength={160} defaultValue={existing?.title}/></Field><Field label="Assessment type"><select name="type" defaultValue={existing?.type || 'exam'}>{['assignment','quiz','exam','project','other'].map(t=><option key={t} value={t}>{t}</option>)}</select></Field><div className="form-two"><Field label="Maximum raw marks"><Decimal name="max" value={existing?.max || ''} min="0.01" max="1000000"/></Field><Field label="Weight in final course (%)"><Decimal name="weight" value={existing?.weight || ''} min="0.01"/></Field></div><div className="form-two"><Field label="Earned score (blank = ungraded)"><Decimal name="score" value={existing?.score || ''} max="1000000" optional/></Field><Field label="Allowed mark increment (optional)"><Decimal name="increment" value={existing?.increment || ''} min="0.01" max="1000000" optional/></Field></div><Field label="Assessment date (optional)"><input type="date" name="due" defaultValue={existing?.due}/></Field><p className="fine">Scores, maxima, weights, and increments accept up to two decimal places. Explicit 0 is scored. Set increment 1 for whole marks or 0.5 for half marks; blank makes no discrete-minimum claim.</p><FormError error={error}/><button className="primary" disabled={disabled}>{existing?'Save assessment':'Add assessment'}</button></form>;
}
function SemesterGoal({data,save,disabled,error,periodId}: AcademicProps & {periodId:string}) {
  const period=data.periods.find(p=>p.id===periodId)!;
  return <form className="academic-form details-content" onSubmit={e=>{e.preventDefault();void save('semester-goal',{...Object.fromEntries(new FormData(e.currentTarget)),id:periodId});}}><Field label="Goal grading system"><select name="ruleId" defaultValue={period.goalRuleId}><option value="">Choose a grade-point scale</option>{data.gradeRules.filter(r=>r.scale!=='percentage').map(r=><option key={r.id} value={r.id}>{r.name} v{r.version} · maximum {r.maxPoints}</option>)}</select></Field><Field label="Target semester GPA (blank clears goal)"><Decimal name="value" value={period.goal} max="1000" optional step="0.0001"/></Field><p className="fine">Compared at full precision. Display rounding does not establish achievement.</p><FormError error={error}/><button className="primary" disabled={disabled}>Save semester goal</button></form>;
}
