'use client';
import { useState } from 'react';
import type { Band, GradeRule } from '@/lib/academic-types';
import { validateRule } from '@/lib/academic-data';
import { courseCalculation, mapGrade } from '@/lib/academic-calculations';
import type { Course } from '@/lib/model';
import { Field, FormError, type AcademicProps } from './academic-shared';

const example: Band[] = [ ['F','0','0'],['D','50','1'],['C','60','2'],['C+','65','2.5'],['B','70','3'],['B+','75','3.33'],['A−','80','3.67'],['A','85','4'] ].map(([label,lower,points]) => ({label,lower,points}));
export function RulePreview({ rule }: {rule: GradeRule}) {
  return <div className="rule-preview"><p><strong>{rule.name}</strong> · version {rule.version} · {rule.scale === 'percentage' ? 'Percentage only; no GPA' : `${rule.maxPoints}-point scale`} · {rule.rounding === 'none' ? 'No mapping rounding' : 'Nearest whole, half-up'}</p><ul>{rule.bands.map((b,i) => <li key={b.label}>{b.lower} ≤ mapped marks {i === rule.bands.length-1 ? '≤ 100' : `< ${rule.bands[i+1].lower}`} → <strong>{b.label}</strong>{rule.scale !== 'percentage' && ` · ${b.points} points`}</li>)}</ul></div>;
}
export default function GradingRules(props: AcademicProps) {
  const [previous,setPrevious] = useState(''), [generation,setGeneration] = useState(0);
  const prior = props.data.gradeRules.find(r => r.id === previous);
  return <details className="panel academic-details" id="grading-rules"><summary>University grading systems and versions</summary><div className="details-content"><p>Enter your own fixed boundaries. Scale selection and university name never supply or convert a table. The first band starts at 0; each next lower threshold defines the previous upper bound, covering 0–100 exactly once.</p><Field label="Rule version to use as a draft"><select value={previous} onChange={e => {setPrevious(e.target.value);setGeneration(n=>n+1);}}><option value="">New grading system</option>{props.data.gradeRules.map(r => <option key={r.id} value={r.id}>{r.name} · v{r.version} · {r.maxPoints}-point</option>)}</select></Field><RuleEditor key={previous+generation} {...props} previous={prior} onSaved={() => setGeneration(n=>n+1)}/>{props.data.gradeRules.length > 0 && <details className="sub-details"><summary>Saved versions (read-only)</summary>{props.data.gradeRules.map(r => <RulePreview key={r.id} rule={r}/>)}</details>}</div></details>;
}
function RuleEditor({data,save,disabled,error,previous,onSaved}: AcademicProps & {previous?: GradeRule;onSaved:()=>void}) {
  const [id] = useState(crypto.randomUUID());
  const [name,setName] = useState(previous?.name || ''), [scale,setScale] = useState<GradeRule['scale']>(previous?.scale || '4');
  const [maxPoints,setMax] = useState(previous?.maxPoints || '4'), [rounding,setRounding] = useState(previous?.rounding || 'none');
  const [bands,setBands] = useState<Band[]>(previous?.bands.map(b => ({...b})) || [{label:'',lower:'0',points:''}]);
  const [selected,setSelected] = useState<string[]>([]), [reviewed,setReviewed] = useState(false), [sample,setSample] = useState(false);
  const payload = {id,previousId:previous?.id || '',name,scale,maxPoints,rounding,bands,courseIds:selected,reviewed};
  let preview: GradeRule | null = null, validation = '';
  try { preview = validateRule(payload,Date.now(),previous); } catch(e) {validation=(e as Error).message;}
  function update(index:number,key:keyof Band,value:string) {setReviewed(false);setBands(bands.map((b,i) => i===index ? {...b,[key]:value} : b));}
  const candidates = data.courses.filter(c => !c.archived && !courseCalculation(data,c).final);
  return <form className="academic-form" onSubmit={async e => {e.preventDefault();if (reviewed && await save('rule',payload)) onSaved();}}>
    <Field label="Grading system name"><input required maxLength={160} value={name} onChange={e => {setName(e.target.value);setReviewed(false);}} placeholder="Your university’s fixed rules"/></Field><div className="form-two"><Field label="Academic scale"><select value={scale} onChange={e => {setScale(e.target.value as GradeRule['scale']);setReviewed(false);}}><option value="percentage">Percentage only</option><option value="4">4.0 GPA</option><option value="10">10-point GPA</option><option value="custom">Custom GPA</option></select></Field>{scale === 'custom' && <Field label="Maximum grade points"><input required type="number" min="0.01" max="1000" step="0.01" value={maxPoints} onChange={e => {setMax(e.target.value);setReviewed(false);}}/></Field>}</div>
    <Field label="Rounding before grade mapping"><select value={rounding} onChange={e => {setRounding(e.target.value as GradeRule['rounding']);setReviewed(false);}}><option value="none">No rounding (raw percentage)</option><option value="half-up">Nearest whole number, half-up</option></select></Field>
    <div className="row-spread"><h3>Grade bands</h3><button className="secondary" type="button" onClick={() => {setBands(example.map(b=>({...b})));setName('Example — review for your university');setScale('4');setMax('4');setSample(true);setReviewed(false);}}>Load labelled example</button></div>{sample && <p className="banner">Sample data only. Verify every boundary and point value before saving this as your own rule set.</p>}
    {bands.map((b,i) => <fieldset className="grade-band" key={i}><legend>Band {i+1}</legend><Field label={`Band ${i+1} grade label`}><input required maxLength={30} value={b.label} onChange={e=>update(i,'label',e.target.value)}/></Field><Field label={`Band ${i+1} lower percentage`}><input required type="number" min="0" max="100" step="0.01" value={b.lower} onChange={e=>update(i,'lower',e.target.value)}/></Field>{scale !== 'percentage' && <Field label={`Band ${i+1} grade points`}><input required type="number" min="0" max={scale === 'custom' ? maxPoints : scale} step="0.0001" value={b.points} onChange={e=>update(i,'points',e.target.value)}/></Field>}<button className="text-button" type="button" disabled={bands.length===1} onClick={()=>{setBands(bands.filter((_,n)=>n!==i));setReviewed(false);}}>Remove band {i+1}</button></fieldset>)}
    <button type="button" className="secondary" disabled={bands.length>=30} onClick={()=>{setBands([...bands,{label:'',lower:'',points:''}]);setReviewed(false);}}>Add grade band</button>
    <h3>Unsaved rule preview</h3>{preview ? <RulePreview rule={preview}/> : <p className="banner">{validation}</p>}
    <fieldset className="affected-courses"><legend>Apply this new version to selected active courses</legend>{candidates.map(c => <label className="checkbox-field" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>{setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id));setReviewed(false);}}/>{c.name} · currently {data.gradeRules.find(r=>r.id===c.gradeRuleId)?.name || 'no mapping'}{c.target?.kind === 'grade' && ` · grade target ${c.target.value} will use the new boundaries`}</label>)}{!candidates.length && <p className="fine">No active incomplete courses. You can save the version without applying it.</p>}<p className="fine">Completed and archived courses keep their old versions. Explicit historical remapping is available in each course planner.</p></fieldset>
    <label className="checkbox-field"><input type="checkbox" required checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed these ranges, points, rounding, and selected courses.</label><FormError error={error}/><button className="primary" disabled={disabled || !preview || !reviewed}>Save grading version</button>
  </form>;
}
export function CourseRuleForm({course,data,save,disabled,error}: AcademicProps & {course: Course}) {
  const [selected,setSelected] = useState(course.gradeRuleId);
  const calc = courseCalculation(data,course), next = data.gradeRules.find(r=>r.id===selected);
  const mapped = next && calc.final ? mapGrade(calc.earned,next) : null;
  const old = data.gradeRules.find(r=>r.id===course.gradeRuleId);
  return <form className="academic-form" onSubmit={e => {e.preventDefault(); if ((!calc.final && !course.archived) || window.confirm('Apply this reviewed rule version to this historical course? Raw scores are preserved; the old version remains in the change history.')) void save('assign-rule',{id:course.id,ruleId:selected,confirm:true});}}><Field label="Course grading version"><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a saved version</option>{data.gradeRules.map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version} · {r.maxPoints}-point</option>)}</select></Field><p className="fine">Currently {old ? `${old.name} v${old.version}` : 'percentage-only planning (no mapping)'}. New version: {next ? `${next.name} v${next.version}` : 'not selected'}.</p>{calc.final && <p className="banner">Historical remap preview: raw {calc.earned.fixed(4)}% stays unchanged. {calc.grade ? `${calc.grade.label} (${calc.grade.points || 'no GPA'} points)` : 'No mapped grade'} → {mapped ? `${mapped.label} (${mapped.points || 'no GPA'} points), mapped marks ${mapped.mapped.fixed(4)}%` : 'No mapping selected'}.</p>}{course.target?.kind==='grade' && next && <p className="fine">Current grade target: {course.target.value}. {next.bands.some(b=>b.label===course.target!.value) ? 'The target will use the chosen version’s boundaries.' : 'This label is absent in the new version; choose a new target after saving.'}</p>}<FormError error={error}/><button className="primary" disabled={disabled || !next || selected===course.gradeRuleId}>{calc.final || course.archived ? 'Review and remap historical result' : 'Apply selected grading version'}</button>{course.ruleHistory.length>0 && <details className="sub-details"><summary>Rule assignment history</summary><ul>{course.ruleHistory.map((h,i)=><li key={i}>{h.at} · {data.gradeRules.find(r=>r.id===h.from)?.name || 'No mapping'} → {data.gradeRules.find(r=>r.id===h.to)?.name} v{data.gradeRules.find(r=>r.id===h.to)?.version}</li>)}</ul></details>}</form>;
}
